// This file is auto-generated by Next.js
// DO NOT EDIT

/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE:
// Managed automatically by Next.js
// See: https://nextjs.org/docs/app/api-reference/config/typescript
